### ISSUE TITLE
Lesson 23 Classwork Task 1, Lesson 23 Homework Task 2

### ISSUE THREAD

**Issue by DinamickaDevelopment** [simakovEvgen/DD_CompetencyCenter-Simakov#5]
Не выполнены условия задачи(исползуется Webpack, а не browserify)

**Comment by simakovEvgen** [comment]
/*
* Class Work
*
* ### Задача 1
*
* Создайте папку app. В ней создайте файл index.html и папку src. В папке src создайте 2 файла:
* файл app.js с произвольным кодом
* файл main.js, который загрузит код файла app.js
* С помощью webpack свяжите эти страницы в файл bundle.js и подключите его к странице index.html.
*/

/*
* Home Work
*
* ### Задача 2
*
* Переделайте задание из предыдущей задачи с использованием browserify. 
*/


Выполнил соответственно заданиям
